#!node

/*/
    this script generates the `dist/neutralino.d.ts` file definitions
    then inject the global declarations (Neutralino, NL_VERSION, ...)
    it is necessary to move the global declarations of `src/index.ts` to a private declaration file.

    After testing many different build solutions and tools, it seems like there isn't a good solution to translate a set of modules into a single iife file.
    I chose npm-dts because it is simple and produces a readable definitions.
    However, it doesn't have a lot of features and we cannot intercept the generated output, this script is there for that.
/*/

//@ts-check

const path = require ('path')
const fs   = require ('fs')

const { version } = require ('./package.json')
const output = path.resolve (process.cwd (), 'dist/neutralino.d.ts')

new (require ('npm-dts')).Generator ({
    entry  : path.resolve(process.cwd (), 'src/index.ts'),
    tsc    : '--extendedDiagnostics',
    output : output,
})
.generate ()
.then (() => fs.readFileSync (output, { encoding: "utf8" }))
.then (content => fs.writeFileSync (output,
`// Type definitions for Neutralino ${version}
// Project: https://github.com/neutralinojs
// Definitions project: https://github.com/corbane/neutralino.js

${content}

declare const Neutralino: typeof import('neutralino-client-library/src/index')

/** Exists but not documented: https://neutralino.js.org/docs/developer-environment/global-variables */
declare const NL_TOKEN: string;

/** Operating system name: Linux, Windows, or Darwin */
declare const NL_OS: "Linux"|"Windows"|"Darwin";

/** Application identifier */
declare const NL_APPID: string;

/** Application port */
declare const NL_PORT: number;

/** Mode of the application: window, browser, or cloud */
declare const NL_MODE: "window"|"browser"|"cloud";

/** Neutralinojs server version */
declare const NL_VERSION: string;

/** Neutralinojs client version */
declare const NL_CVERSION: "${version}";

/** Current working directory */
declare const NL_CWD: string;

/** Application path */
declare const NL_PATH: string;

/** Command-line arguments */
declare const NL_ARGS: string[];

/** Current process's identifier */
declare const NL_PID: number

`, { encoding: "utf8" }))
