name: Create release

on: 
  workflow_dispatch:
    inputs: 
      version: 
        type: text
        description: "Version number Eg: 4.2.0"
env:
  VERSION: ${{inputs.version}}
  VERSION_WITH_V: "v${{inputs.version}}"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      
    - name: Install and build
      run: |
        npm ci
        npm run build
        if [ -e ./dist/neutralino.js ]; then echo "OK"; else echo "ERR"; exit 1; fi
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: lib_dist
        path: ./dist/
        
  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v6
      
    - name: Download build artifacts 
      uses: actions/download-artifact@v8
      with:
        name: lib_dist
        path: ./dist/
        
    - name: Create Release notes
      run: |
        chmod +x ./scripts/rz.py
        ./scripts/rz.py create $VERSION
        
    - name: Create branch for release
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git checkout -b $VERSION_WITH_V
        git push origin $VERSION_WITH_V
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create the new release
      run: |
          gh release create $VERSION_WITH_V \
          dist/*.* \
          --title "Neutralino.js $VERSION_WITH_V released!" \
          --notes-file .tmprz/release_notes.md \
          --prerelease
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Send a pull request for the modified changelog
      run: |
        branch=changelog-update-$VERSION_WITH_V
        git checkout -b $branch
        git add CHANGELOG.md
        git commit -m "Update changelog for $VERSION_WITH_V"
        git push origin $branch
        gh pr create \
        --title "Update changelog after $VERSION_WITH_V release" \
        --body "This pull request updates CHANGELOG.md file after the recent release." \
        --assignee "${{github.actor}}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Clean Release Notes
      run: |
        ./scripts/rz.py cleanup
        
  publish-to-npm:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v6
      
    - uses: actions/setup-node@v6
      with:
        node-version: "24.x"
        registry-url: "https://registry.npmjs.org"
        scope: "@neutralinojs"
        
    - name: Install dependencies
      run: npm ci

    - name: Publish to the NPM registry
      run: |
        npm run build
        npm publish --access=public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Send a Discord message
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: |
          Neutralino.js ${{ env.VERSION_WITH_V }} released 🚀
          Changelog: https://github.com/neutralinojs/neutralino.js/releases/tag/${{ env.VERSION_WITH_V }}
